namespace Atom;

/// <summary>
///     This build definition is responsible for generating the C# code for the .NET CLI wrapper.
/// </summary>
/// <remarks>
///     It uses the `dotnet --cli-schema` command to obtain the latest .NET CLI command structure,
///     then parses this schema and generates strongly-typed C# interfaces, implementations, and
///     option classes for each `dotnet` command. The generated files are placed in the
///     `DecSm.Atom.Module.Dotnet/Cli/Generated` directory.
/// </remarks>
[BuildDefinition]
[GenerateEntryPoint]
internal sealed partial class Build : MinimalBuildDefinition
{
    /// <summary>
    ///     The target that generates the .NET CLI wrapper code.
    /// </summary>
    /// <remarks>
    ///     This target performs the following steps:
    ///     <list type="number">
    ///         <item>
    ///             <description>Executes `dotnet --cli-schema` to retrieve the .NET CLI's command schema in JSON format.</description>
    ///         </item>
    ///         <item>
    ///             <description>Parses the JSON schema into a structured command model.</description>
    ///         </item>
    ///         <item>
    ///             <description>Flattens the command hierarchy, prefixing subcommand names with their parent commands.</description>
    ///         </item>
    ///         <item>
    ///             <description>
    ///                 Filters out specific commands (e.g., "completions script", "help") that should not have
    ///                 generated wrappers.
    ///             </description>
    ///         </item>
    ///         <item>
    ///             <description>
    ///                 For each valid command, it generates a C# interface, an implementation class, and an options
    ///                 record.
    ///             </description>
    ///         </item>
    ///         <item>
    ///             <description>Writes these generated C# files to the `DecSm.Atom.Module.Dotnet/Cli/Generated` directory.</description>
    ///         </item>
    ///     </list>
    ///     This process ensures that the `DecSm.Atom.Module.Dotnet` always provides an up-to-date and type-safe API for the
    ///     .NET CLI.
    /// </remarks>
    private Target GenerateDotnetCliCode =>
        t => t.Executes(async () =>
        {
            Logger.LogInformation("Generating .NET CLI wrapper code...");

            // Get the .NET CLI schema
            var result = await ProcessRunner.RunAsync(new("dotnet", "--cli-schema"));
            var cliSchema = JsonDocument.Parse(result.Output);

            // Parse the schema
            var rootCommand = DotnetCliParser.GetCommand("dotnet", cliSchema.RootElement);

            if (rootCommand is null)
                throw new InvalidOperationException("Failed to parse dotnet CLI schema.");

            // Flatten subcommands
            var flattenedCommands = new List<Command>();

            foreach (var subCommand in rootCommand.SubCommands)
                DotnetCliParser.FlattenCommands(string.Empty, subCommand, flattenedCommands);

            if (!FileSystem.Directory.Exists(FileSystem.AtomRootDirectory /
                                             "DecSm.Atom.Module.Dotnet" /
                                             "Cli" /
                                             "Generated"))
                FileSystem.Directory.CreateDirectory(FileSystem.AtomRootDirectory /
                                                     "DecSm.Atom.Module.Dotnet" /
                                                     "Cli" /
                                                     "Generated");

            // Filter commands
            // Also filter out internal/special commands
            flattenedCommands = flattenedCommands
                .Where(x => x.Name.ToLowerInvariant() is not "completions script" and not "help" &&
                            !x.Name.StartsWith('-'))
                .ToList();

            // Generate and write code for each command
            foreach (var command in flattenedCommands)
            {
                var writer = new CsharpWriter();

                writer.WriteLine("// <auto-generated/>");
                writer.WriteLine(string.Empty);
                writer.WriteLine("#nullable enable");
                writer.WriteLine(string.Empty);
                writer.WriteLine("namespace DecSm.Atom.Module.Dotnet.Cli;");
                writer.WriteLine(string.Empty);

                DotnetCliGenerator.GenerateInterfaceCode(writer, command);
                DotnetCliGenerator.GenerateImplementationCode(writer, command);
                DotnetCliGenerator.GenerateOptionsCode(writer, command);

                await FileSystem.File.WriteAllTextAsync(FileSystem.AtomRootDirectory /
                                                        "DecSm.Atom.Module.Dotnet" /
                                                        "Cli" /
                                                        "Generated" /
                                                        $"{CsharpWriter.ToPascalCase(command.Name)}.cs",
                    writer.ToString());
            }

            Logger.LogInformation("Successfully generated .NET CLI wrapper code for {CommandCount} commands.",
                flattenedCommands.Count);
        });
}
