global using System.IO.Abstractions.TestingHelpers;
global using Invex.Atom.Build;
global using Invex.Atom.Build.Args;
global using Invex.Atom.Build.Definition;
global using Invex.Atom.Build.Exceptions;
global using Invex.Atom.Build.Hosting;
global using Invex.Atom.Module.Dotnet.Helpers;
global using Invex.Atom.TestUtils;
global using FakeItEasy;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using NUnit.Framework;
global using Shouldly;
global using static Invex.Atom.TestUtils.TestUtils;
