name: Test_Devops_Build

trigger:
  branches:
    include: [ main ]
pr:
  branches:
    include: [ main ]
variables:
  - group: Atom

jobs:

  - job: SetupBuildInfo
    displayName: SetupBuildInfo
    pool:
      vmImage: ubuntu-latest
    steps:

      - checkout: self
        enabled: true
        fetchDepth: 0

      - task: UseDotNet@2
        displayName: Setup .NET 10.0.x
        inputs:
          version: 10.0.x

      - script: dotnet run --project _atom/_atom.csproj SetupBuildInfo --skip --headless
        displayName: SetupBuildInfo
        name: SetupBuildInfo
        env:
          nuget-dry-run: true

  - job: PackProjects
    displayName: PackProjects
    pool:
      vmImage: ubuntu-latest
    steps:

      - checkout: self
        enabled: true
        fetchDepth: 0

      - task: UseDotNet@2
        displayName: Setup .NET 10.0.x
        inputs:
          version: 10.0.x

      - script: dotnet run --project _atom/_atom.csproj PackProjects --skip --headless
        displayName: PackProjects
        name: PackProjects
        env:
          nuget-dry-run: true

      - task: PublishPipelineArtifact@1
        displayName: Invex.Atom.Build
        inputs:
          artifactName: Invex.Atom.Build
          targetPath: $(Build.BinariesDirectory)/Invex.Atom.Build

      - task: PublishPipelineArtifact@1
        displayName: Invex.Atom.Workflows
        inputs:
          artifactName: Invex.Atom.Workflows
          targetPath: $(Build.BinariesDirectory)/Invex.Atom.Workflows

      - task: PublishPipelineArtifact@1
        displayName: Invex.Atom.Module.AzureKeyVault
        inputs:
          artifactName: Invex.Atom.Module.AzureKeyVault
          targetPath: $(Build.BinariesDirectory)/Invex.Atom.Module.AzureKeyVault

      - task: PublishPipelineArtifact@1
        displayName: Invex.Atom.Module.AzureStorage
        inputs:
          artifactName: Invex.Atom.Module.AzureStorage
          targetPath: $(Build.BinariesDirectory)/Invex.Atom.Module.AzureStorage

      - task: PublishPipelineArtifact@1
        displayName: Invex.Atom.Module.DevopsWorkflows
        inputs:
          artifactName: Invex.Atom.Module.DevopsWorkflows
          targetPath: $(Build.BinariesDirectory)/Invex.Atom.Module.DevopsWorkflows

      - task: PublishPipelineArtifact@1
        displayName: Invex.Atom.Module.Dotnet
        inputs:
          artifactName: Invex.Atom.Module.Dotnet
          targetPath: $(Build.BinariesDirectory)/Invex.Atom.Module.Dotnet

      - task: PublishPipelineArtifact@1
        displayName: Invex.Atom.Module.GitVersion
        inputs:
          artifactName: Invex.Atom.Module.GitVersion
          targetPath: $(Build.BinariesDirectory)/Invex.Atom.Module.GitVersion

      - task: PublishPipelineArtifact@1
        displayName: Invex.Atom.Module.GithubWorkflows
        inputs:
          artifactName: Invex.Atom.Module.GithubWorkflows
          targetPath: $(Build.BinariesDirectory)/Invex.Atom.Module.GithubWorkflows

  - job: PackTool
    displayName: PackTool
    strategy:
      matrix:
        001_windows-latest:
          job-runs-on: 'windows-latest'
        002_ubuntu-latest:
          job-runs-on: 'ubuntu-latest'
        003_macos-latest:
          job-runs-on: 'macos-latest'
    pool:
      vmImage: $(job-runs-on)
    steps:

      - checkout: self
        enabled: true
        fetchDepth: 0

      - task: UseDotNet@2
        displayName: Setup .NET 10.0.x
        inputs:
          version: 10.0.x

      - script: dotnet run --project _atom/_atom.csproj PackTool --skip --headless
        displayName: PackTool
        name: PackTool
        env:
          nuget-dry-run: true
          job-runs-on: $(job-runs-on)
          build-slice: $(job-runs-on)

      - task: PublishPipelineArtifact@1
        displayName: Invex.Atom.Tool
        inputs:
          artifactName: Invex.Atom.Tool-$(job-runs-on)
          targetPath: $(Build.BinariesDirectory)/Invex.Atom.Tool

  - job: TestProjects
    displayName: TestProjects
    strategy:
      matrix:
        001_windows-latest_net8-0:
          job-runs-on: 'windows-latest'
          test-framework: 'net8.0'
        002_ubuntu-latest_net8-0:
          job-runs-on: 'ubuntu-latest'
          test-framework: 'net8.0'
        003_macos-latest_net8-0:
          job-runs-on: 'macos-latest'
          test-framework: 'net8.0'
        004_windows-latest_net9-0:
          job-runs-on: 'windows-latest'
          test-framework: 'net9.0'
        005_ubuntu-latest_net9-0:
          job-runs-on: 'ubuntu-latest'
          test-framework: 'net9.0'
        006_macos-latest_net9-0:
          job-runs-on: 'macos-latest'
          test-framework: 'net9.0'
        007_windows-latest_net10-0:
          job-runs-on: 'windows-latest'
          test-framework: 'net10.0'
        008_ubuntu-latest_net10-0:
          job-runs-on: 'ubuntu-latest'
          test-framework: 'net10.0'
        009_macos-latest_net10-0:
          job-runs-on: 'macos-latest'
          test-framework: 'net10.0'
    pool:
      vmImage: $(job-runs-on)
    steps:

      - checkout: self
        enabled: true
        fetchDepth: 0

      - task: UseDotNet@2
        displayName: Setup .NET 10.0.x
        inputs:
          version: 10.0.x

      - task: UseDotNet@2
        displayName: Setup .NET 8.0.x
        inputs:
          version: 8.0.x

      - task: UseDotNet@2
        displayName: Setup .NET 9.0.x
        inputs:
          version: 9.0.x

      - script: dotnet run --project _atom/_atom.csproj TestProjects --skip --headless
        displayName: TestProjects
        name: TestProjects
        env:
          nuget-dry-run: true
          job-runs-on: $(job-runs-on)
          test-framework: $(test-framework)
          build-slice: $(job-runs-on)-$(test-framework)

      - task: PublishPipelineArtifact@1
        displayName: Atom.Tests
        inputs:
          artifactName: Atom.Tests-$(job-runs-on)-$(test-framework)
          targetPath: $(Build.BinariesDirectory)/Atom.Tests

      - task: PublishPipelineArtifact@1
        displayName: Invex.Atom.Build.Tests
        inputs:
          artifactName: Invex.Atom.Build.Tests-$(job-runs-on)-$(test-framework)
          targetPath: $(Build.BinariesDirectory)/Invex.Atom.Build.Tests

      - task: PublishPipelineArtifact@1
        displayName: Invex.Atom.Build.Analyzers.Tests
        inputs:
          artifactName: Invex.Atom.Build.Analyzers.Tests-$(job-runs-on)-$(test-framework)
          targetPath: $(Build.BinariesDirectory)/Invex.Atom.Build.Analyzers.Tests

      - task: PublishPipelineArtifact@1
        displayName: Invex.Atom.Build.SourceGenerators.Tests
        inputs:
          artifactName: Invex.Atom.Build.SourceGenerators.Tests-$(job-runs-on)-$(test-framework)
          targetPath: $(Build.BinariesDirectory)/Invex.Atom.Build.SourceGenerators.Tests

      - task: PublishPipelineArtifact@1
        displayName: Invex.Atom.Module.DevopsWorkflows.Tests
        inputs:
          artifactName: Invex.Atom.Module.DevopsWorkflows.Tests-$(job-runs-on)-$(test-framework)
          targetPath: $(Build.BinariesDirectory)/Invex.Atom.Module.DevopsWorkflows.Tests

      - task: PublishPipelineArtifact@1
        displayName: Invex.Atom.Module.Dotnet.Tests
        inputs:
          artifactName: Invex.Atom.Module.Dotnet.Tests-$(job-runs-on)-$(test-framework)
          targetPath: $(Build.BinariesDirectory)/Invex.Atom.Module.Dotnet.Tests

      - task: PublishPipelineArtifact@1
        displayName: Invex.Atom.Module.GithubWorkflows.Tests
        inputs:
          artifactName: Invex.Atom.Module.GithubWorkflows.Tests-$(job-runs-on)-$(test-framework)
          targetPath: $(Build.BinariesDirectory)/Invex.Atom.Module.GithubWorkflows.Tests

      - task: PublishPipelineArtifact@1
        displayName: Invex.Atom.Workflows.Tests
        inputs:
          artifactName: Invex.Atom.Workflows.Tests-$(job-runs-on)-$(test-framework)
          targetPath: $(Build.BinariesDirectory)/Invex.Atom.Workflows.Tests

      - task: PublishPipelineArtifact@1
        displayName: Invex.Atom.Tool.Tests
        inputs:
          artifactName: Invex.Atom.Tool.Tests-$(job-runs-on)-$(test-framework)
          targetPath: $(Build.BinariesDirectory)/Invex.Atom.Tool.Tests

  - job: PushToNugetDevops
    displayName: PushToNugetDevops
    dependsOn: [ TestProjects, PackProjects, PackTool, SetupBuildInfo ]
    variables:
      - name: build-id
        value: $[ dependencies.SetupBuildInfo.outputs['SetupBuildInfo.build-id'] ]
    pool:
      vmImage: ubuntu-latest
    steps:

      - checkout: self
        enabled: true
        fetchDepth: 0

      - task: UseDotNet@2
        displayName: Setup .NET 10.0.x
        inputs:
          version: 10.0.x

      - task: DownloadPipelineArtifact@2
        displayName: Invex.Atom.Build
        inputs:
          artifact: Invex.Atom.Build
          path: $(Build.ArtifactStagingDirectory)/Invex.Atom.Build

      - task: DownloadPipelineArtifact@2
        displayName: Invex.Atom.Workflows
        inputs:
          artifact: Invex.Atom.Workflows
          path: $(Build.ArtifactStagingDirectory)/Invex.Atom.Workflows

      - task: DownloadPipelineArtifact@2
        displayName: Invex.Atom.Module.AzureKeyVault
        inputs:
          artifact: Invex.Atom.Module.AzureKeyVault
          path: $(Build.ArtifactStagingDirectory)/Invex.Atom.Module.AzureKeyVault

      - task: DownloadPipelineArtifact@2
        displayName: Invex.Atom.Module.AzureStorage
        inputs:
          artifact: Invex.Atom.Module.AzureStorage
          path: $(Build.ArtifactStagingDirectory)/Invex.Atom.Module.AzureStorage

      - task: DownloadPipelineArtifact@2
        displayName: Invex.Atom.Module.DevopsWorkflows
        inputs:
          artifact: Invex.Atom.Module.DevopsWorkflows
          path: $(Build.ArtifactStagingDirectory)/Invex.Atom.Module.DevopsWorkflows

      - task: DownloadPipelineArtifact@2
        displayName: Invex.Atom.Module.Dotnet
        inputs:
          artifact: Invex.Atom.Module.Dotnet
          path: $(Build.ArtifactStagingDirectory)/Invex.Atom.Module.Dotnet

      - task: DownloadPipelineArtifact@2
        displayName: Invex.Atom.Module.GitVersion
        inputs:
          artifact: Invex.Atom.Module.GitVersion
          path: $(Build.ArtifactStagingDirectory)/Invex.Atom.Module.GitVersion

      - task: DownloadPipelineArtifact@2
        displayName: Invex.Atom.Module.GithubWorkflows
        inputs:
          artifact: Invex.Atom.Module.GithubWorkflows
          path: $(Build.ArtifactStagingDirectory)/Invex.Atom.Module.GithubWorkflows

      - task: DownloadPipelineArtifact@2
        displayName: Invex.Atom.Tool
        inputs:
          artifact: Invex.Atom.Tool-windows-latest
          path: $(Build.ArtifactStagingDirectory)/Invex.Atom.Tool

      - task: DownloadPipelineArtifact@2
        displayName: Invex.Atom.Tool
        inputs:
          artifact: Invex.Atom.Tool-ubuntu-latest
          path: $(Build.ArtifactStagingDirectory)/Invex.Atom.Tool

      - task: DownloadPipelineArtifact@2
        displayName: Invex.Atom.Tool
        inputs:
          artifact: Invex.Atom.Tool-macos-latest
          path: $(Build.ArtifactStagingDirectory)/Invex.Atom.Tool

      - script: dotnet run --project _atom/_atom.csproj PushToNugetDevops --skip --headless
        displayName: PushToNugetDevops
        name: PushToNugetDevops
        env:
          build-id: $(build-id)
          nuget-push-api-key: $(NUGET_PUSH_API_KEY)
          nuget-dry-run: true
