name: Test_Devops_Build

trigger:
  branches:
    include: [ main ]
pr:
  branches:
    include: [ main ]
variables:
  - group: Atom

jobs:

  - job: SetupBuildInfo
    displayName: SetupBuildInfo
    pool:
      vmImage: ubuntu-latest
    steps:

      - checkout: self
        enabled: true
        fetchDepth: 0

      - task: UseDotNet@2
        displayName: Setup .NET 10.0.x
        inputs:
          version: 10.0.x

      - script: dotnet run --project _atom/_atom.csproj SetupBuildInfo --skip --headless
        displayName: SetupBuildInfo
        name: SetupBuildInfo
        env:
          nuget-dry-run: true

  - job: PackProjects
    displayName: PackProjects
    pool:
      vmImage: ubuntu-latest
    steps:

      - checkout: self
        enabled: true
        fetchDepth: 0

      - task: UseDotNet@2
        displayName: Setup .NET 10.0.x
        inputs:
          version: 10.0.x

      - script: dotnet run --project _atom/_atom.csproj PackProjects --skip --headless
        displayName: PackProjects
        name: PackProjects
        env:
          nuget-dry-run: true

      - task: PublishPipelineArtifact@1
        displayName: DecSm.Atom.Build
        inputs:
          artifactName: DecSm.Atom.Build
          targetPath: $(Build.BinariesDirectory)/DecSm.Atom.Build

      - task: PublishPipelineArtifact@1
        displayName: DecSm.Atom.FileSystem
        inputs:
          artifactName: DecSm.Atom.FileSystem
          targetPath: $(Build.BinariesDirectory)/DecSm.Atom.FileSystem

      - task: PublishPipelineArtifact@1
        displayName: DecSm.Atom.Process
        inputs:
          artifactName: DecSm.Atom.Process
          targetPath: $(Build.BinariesDirectory)/DecSm.Atom.Process

      - task: PublishPipelineArtifact@1
        displayName: DecSm.Atom.SemanticVersion
        inputs:
          artifactName: DecSm.Atom.SemanticVersion
          targetPath: $(Build.BinariesDirectory)/DecSm.Atom.SemanticVersion

      - task: PublishPipelineArtifact@1
        displayName: DecSm.Atom.Workflows
        inputs:
          artifactName: DecSm.Atom.Workflows
          targetPath: $(Build.BinariesDirectory)/DecSm.Atom.Workflows

      - task: PublishPipelineArtifact@1
        displayName: DecSm.StructuredText
        inputs:
          artifactName: DecSm.StructuredText
          targetPath: $(Build.BinariesDirectory)/DecSm.StructuredText

      - task: PublishPipelineArtifact@1
        displayName: DecSm.StructuredText.AzureDevopsPipelines
        inputs:
          artifactName: DecSm.StructuredText.AzureDevopsPipelines
          targetPath: $(Build.BinariesDirectory)/DecSm.StructuredText.AzureDevopsPipelines

      - task: PublishPipelineArtifact@1
        displayName: DecSm.StructuredText.GithubActions
        inputs:
          artifactName: DecSm.StructuredText.GithubActions
          targetPath: $(Build.BinariesDirectory)/DecSm.StructuredText.GithubActions

      - task: PublishPipelineArtifact@1
        displayName: DecSm.Atom.Module.AzureKeyVault
        inputs:
          artifactName: DecSm.Atom.Module.AzureKeyVault
          targetPath: $(Build.BinariesDirectory)/DecSm.Atom.Module.AzureKeyVault

      - task: PublishPipelineArtifact@1
        displayName: DecSm.Atom.Module.AzureStorage
        inputs:
          artifactName: DecSm.Atom.Module.AzureStorage
          targetPath: $(Build.BinariesDirectory)/DecSm.Atom.Module.AzureStorage

      - task: PublishPipelineArtifact@1
        displayName: DecSm.Atom.Module.DevopsWorkflows
        inputs:
          artifactName: DecSm.Atom.Module.DevopsWorkflows
          targetPath: $(Build.BinariesDirectory)/DecSm.Atom.Module.DevopsWorkflows

      - task: PublishPipelineArtifact@1
        displayName: DecSm.Atom.Module.Dotnet
        inputs:
          artifactName: DecSm.Atom.Module.Dotnet
          targetPath: $(Build.BinariesDirectory)/DecSm.Atom.Module.Dotnet

      - task: PublishPipelineArtifact@1
        displayName: DecSm.Atom.Module.GitVersion
        inputs:
          artifactName: DecSm.Atom.Module.GitVersion
          targetPath: $(Build.BinariesDirectory)/DecSm.Atom.Module.GitVersion

      - task: PublishPipelineArtifact@1
        displayName: DecSm.Atom.Module.GithubWorkflows
        inputs:
          artifactName: DecSm.Atom.Module.GithubWorkflows
          targetPath: $(Build.BinariesDirectory)/DecSm.Atom.Module.GithubWorkflows

  - job: PackTool
    displayName: PackTool
    strategy:
      matrix:
        001_windows-latest:
          job-runs-on: 'windows-latest'
        002_ubuntu-latest:
          job-runs-on: 'ubuntu-latest'
        003_macos-latest:
          job-runs-on: 'macos-latest'
    pool:
      vmImage: $(job-runs-on)
    steps:

      - checkout: self
        enabled: true
        fetchDepth: 0

      - task: UseDotNet@2
        displayName: Setup .NET 10.0.x
        inputs:
          version: 10.0.x

      - script: dotnet run --project _atom/_atom.csproj PackTool --skip --headless
        displayName: PackTool
        name: PackTool
        env:
          nuget-dry-run: true
          job-runs-on: $(job-runs-on)
          build-slice: $(job-runs-on)

      - task: PublishPipelineArtifact@1
        displayName: DecSm.Atom.Tool
        inputs:
          artifactName: DecSm.Atom.Tool-$(job-runs-on)
          targetPath: $(Build.BinariesDirectory)/DecSm.Atom.Tool

  - job: TestProjects
    displayName: TestProjects
    strategy:
      matrix:
        001_windows-latest_net8-0:
          job-runs-on: 'windows-latest'
          test-framework: 'net8.0'
        002_ubuntu-latest_net8-0:
          job-runs-on: 'ubuntu-latest'
          test-framework: 'net8.0'
        003_macos-latest_net8-0:
          job-runs-on: 'macos-latest'
          test-framework: 'net8.0'
        004_windows-latest_net9-0:
          job-runs-on: 'windows-latest'
          test-framework: 'net9.0'
        005_ubuntu-latest_net9-0:
          job-runs-on: 'ubuntu-latest'
          test-framework: 'net9.0'
        006_macos-latest_net9-0:
          job-runs-on: 'macos-latest'
          test-framework: 'net9.0'
        007_windows-latest_net10-0:
          job-runs-on: 'windows-latest'
          test-framework: 'net10.0'
        008_ubuntu-latest_net10-0:
          job-runs-on: 'ubuntu-latest'
          test-framework: 'net10.0'
        009_macos-latest_net10-0:
          job-runs-on: 'macos-latest'
          test-framework: 'net10.0'
    pool:
      vmImage: $(job-runs-on)
    steps:

      - checkout: self
        enabled: true
        fetchDepth: 0

      - task: UseDotNet@2
        displayName: Setup .NET 10.0.x
        inputs:
          version: 10.0.x

      - task: UseDotNet@2
        displayName: Setup .NET 8.0.x
        inputs:
          version: 8.0.x

      - task: UseDotNet@2
        displayName: Setup .NET 9.0.x
        inputs:
          version: 9.0.x

      - script: dotnet run --project _atom/_atom.csproj TestProjects --skip --headless
        displayName: TestProjects
        name: TestProjects
        env:
          nuget-dry-run: true
          job-runs-on: $(job-runs-on)
          test-framework: $(test-framework)
          build-slice: $(job-runs-on)-$(test-framework)

      - task: PublishPipelineArtifact@1
        displayName: DecSm.Atom.Build.Tests
        inputs:
          artifactName: DecSm.Atom.Build.Tests-$(job-runs-on)-$(test-framework)
          targetPath: $(Build.BinariesDirectory)/DecSm.Atom.Build.Tests

      - task: PublishPipelineArtifact@1
        displayName: DecSm.Atom.Build.Analyzers.Tests
        inputs:
          artifactName: DecSm.Atom.Build.Analyzers.Tests-$(job-runs-on)-$(test-framework)
          targetPath: $(Build.BinariesDirectory)/DecSm.Atom.Build.Analyzers.Tests

      - task: PublishPipelineArtifact@1
        displayName: DecSm.Atom.Build.SourceGenerators.Tests
        inputs:
          artifactName: DecSm.Atom.Build.SourceGenerators.Tests-$(job-runs-on)-$(test-framework)
          targetPath: $(Build.BinariesDirectory)/DecSm.Atom.Build.SourceGenerators.Tests

      - task: PublishPipelineArtifact@1
        displayName: DecSm.Atom.Module.DevopsWorkflows.Tests
        inputs:
          artifactName: DecSm.Atom.Module.DevopsWorkflows.Tests-$(job-runs-on)-$(test-framework)
          targetPath: $(Build.BinariesDirectory)/DecSm.Atom.Module.DevopsWorkflows.Tests

      - task: PublishPipelineArtifact@1
        displayName: DecSm.Atom.Module.GithubWorkflows.Tests
        inputs:
          artifactName: DecSm.Atom.Module.GithubWorkflows.Tests-$(job-runs-on)-$(test-framework)
          targetPath: $(Build.BinariesDirectory)/DecSm.Atom.Module.GithubWorkflows.Tests

      - task: PublishPipelineArtifact@1
        displayName: DecSm.Atom.Tool.Tests
        inputs:
          artifactName: DecSm.Atom.Tool.Tests-$(job-runs-on)-$(test-framework)
          targetPath: $(Build.BinariesDirectory)/DecSm.Atom.Tool.Tests

  - job: PushToNugetDevops
    displayName: PushToNugetDevops
    dependsOn: [ TestProjects, PackProjects, PackTool, SetupBuildInfo ]
    variables:
      - name: build-id
        value: $[ dependencies.SetupBuildInfo.outputs['SetupBuildInfo.build-id'] ]
    pool:
      vmImage: ubuntu-latest
    steps:

      - checkout: self
        enabled: true
        fetchDepth: 0

      - task: UseDotNet@2
        displayName: Setup .NET 10.0.x
        inputs:
          version: 10.0.x

      - task: DownloadPipelineArtifact@2
        displayName: DecSm.Atom.Build
        inputs:
          artifact: DecSm.Atom.Build
          path: $(Build.ArtifactStagingDirectory)/DecSm.Atom.Build

      - task: DownloadPipelineArtifact@2
        displayName: DecSm.Atom.FileSystem
        inputs:
          artifact: DecSm.Atom.FileSystem
          path: $(Build.ArtifactStagingDirectory)/DecSm.Atom.FileSystem

      - task: DownloadPipelineArtifact@2
        displayName: DecSm.Atom.Process
        inputs:
          artifact: DecSm.Atom.Process
          path: $(Build.ArtifactStagingDirectory)/DecSm.Atom.Process

      - task: DownloadPipelineArtifact@2
        displayName: DecSm.Atom.SemanticVersion
        inputs:
          artifact: DecSm.Atom.SemanticVersion
          path: $(Build.ArtifactStagingDirectory)/DecSm.Atom.SemanticVersion

      - task: DownloadPipelineArtifact@2
        displayName: DecSm.Atom.Workflows
        inputs:
          artifact: DecSm.Atom.Workflows
          path: $(Build.ArtifactStagingDirectory)/DecSm.Atom.Workflows

      - task: DownloadPipelineArtifact@2
        displayName: DecSm.StructuredText
        inputs:
          artifact: DecSm.StructuredText
          path: $(Build.ArtifactStagingDirectory)/DecSm.StructuredText

      - task: DownloadPipelineArtifact@2
        displayName: DecSm.StructuredText.AzureDevopsPipelines
        inputs:
          artifact: DecSm.StructuredText.AzureDevopsPipelines
          path: $(Build.ArtifactStagingDirectory)/DecSm.StructuredText.AzureDevopsPipelines

      - task: DownloadPipelineArtifact@2
        displayName: DecSm.StructuredText.GithubActions
        inputs:
          artifact: DecSm.StructuredText.GithubActions
          path: $(Build.ArtifactStagingDirectory)/DecSm.StructuredText.GithubActions

      - task: DownloadPipelineArtifact@2
        displayName: DecSm.Atom.Module.AzureKeyVault
        inputs:
          artifact: DecSm.Atom.Module.AzureKeyVault
          path: $(Build.ArtifactStagingDirectory)/DecSm.Atom.Module.AzureKeyVault

      - task: DownloadPipelineArtifact@2
        displayName: DecSm.Atom.Module.AzureStorage
        inputs:
          artifact: DecSm.Atom.Module.AzureStorage
          path: $(Build.ArtifactStagingDirectory)/DecSm.Atom.Module.AzureStorage

      - task: DownloadPipelineArtifact@2
        displayName: DecSm.Atom.Module.DevopsWorkflows
        inputs:
          artifact: DecSm.Atom.Module.DevopsWorkflows
          path: $(Build.ArtifactStagingDirectory)/DecSm.Atom.Module.DevopsWorkflows

      - task: DownloadPipelineArtifact@2
        displayName: DecSm.Atom.Module.Dotnet
        inputs:
          artifact: DecSm.Atom.Module.Dotnet
          path: $(Build.ArtifactStagingDirectory)/DecSm.Atom.Module.Dotnet

      - task: DownloadPipelineArtifact@2
        displayName: DecSm.Atom.Module.GitVersion
        inputs:
          artifact: DecSm.Atom.Module.GitVersion
          path: $(Build.ArtifactStagingDirectory)/DecSm.Atom.Module.GitVersion

      - task: DownloadPipelineArtifact@2
        displayName: DecSm.Atom.Module.GithubWorkflows
        inputs:
          artifact: DecSm.Atom.Module.GithubWorkflows
          path: $(Build.ArtifactStagingDirectory)/DecSm.Atom.Module.GithubWorkflows

      - task: DownloadPipelineArtifact@2
        displayName: DecSm.Atom.Tool
        inputs:
          artifact: DecSm.Atom.Tool-windows-latest
          path: $(Build.ArtifactStagingDirectory)/DecSm.Atom.Tool

      - task: DownloadPipelineArtifact@2
        displayName: DecSm.Atom.Tool
        inputs:
          artifact: DecSm.Atom.Tool-ubuntu-latest
          path: $(Build.ArtifactStagingDirectory)/DecSm.Atom.Tool

      - task: DownloadPipelineArtifact@2
        displayName: DecSm.Atom.Tool
        inputs:
          artifact: DecSm.Atom.Tool-macos-latest
          path: $(Build.ArtifactStagingDirectory)/DecSm.Atom.Tool

      - script: dotnet run --project _atom/_atom.csproj PushToNugetDevops --skip --headless
        displayName: PushToNugetDevops
        name: PushToNugetDevops
        env:
          build-id: $(build-id)
          azure-vault-app-secret: $(AZURE_VAULT_APP_SECRET)
          azure-vault-address: $(AZURE_VAULT_ADDRESS)
          azure-vault-tenant-id: $(AZURE_VAULT_TENANT_ID)
          azure-vault-app-id: $(AZURE_VAULT_APP_ID)
          nuget-dry-run: true
