namespace Atom;

[ConfigureHost]
public partial interface INewAnalyzerExample
{
// 1. Source generator already generates:

// // <auto-generated/>
//
// #nullable enable
//
// using Microsoft.Extensions.Hosting;
//
// namespace Atom;
//
// partial interface INewAnalyzerExample
// {
//
//     [JetBrains.Annotations.UsedImplicitly]
//     protected static partial void ConfigureHostFromINewAnalyzerExample(IHost host);
// }

//  2. The following code is required:

    protected static partial void ConfigureHostFromINewAnalyzerExample(IHost host)
    {
        // Stuff here
    }
}

// 3. TODO: We need to create an analyzer that flags if the above code isn't present, and provides a fix to add it.
