global using DecSm.Atom.Args;
global using DecSm.Atom.Artifacts;
global using DecSm.Atom.Build;
global using DecSm.Atom.Build.Definition;
global using DecSm.Atom.Hosting;
global using DecSm.Atom.Params;
global using DecSm.Atom.TestUtils;
global using DecSm.Atom.Workflows.Definition;
global using DecSm.Atom.Workflows.Definition.Options;
global using DecSm.Atom.Workflows.Definition.Triggers;
global using DecSm.Atom.Workflows.Options;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Shouldly;
global using Spectre.Console.Testing;
global using static DecSm.Atom.TestUtils.TestUtils;
global using Target = DecSm.Atom.Build.Definition.Target;
