global using System.IO.Abstractions.TestingHelpers;
global using Invex.Atom.Build.Args;
global using Invex.Atom.Build.BuildOptions;
global using Invex.Atom.Build.Definition;
global using Invex.Atom.Build.Exceptions;
global using Invex.Atom.Build.Params;
global using Invex.Atom.TestUtils;
global using Invex.Atom.Workflows.Definition;
global using Invex.Atom.Workflows.Definition.Triggers;
global using Invex.Atom.Workflows.Model;
global using Invex.Atom.Workflows.Tests.Builds;
global using Invex.Atom.Workflows.Tests.TestUtils;
global using Invex.Atom.Workflows.Writer;
global using JetBrains.Annotations;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using NUnit.Framework;
global using Shouldly;
global using Spectre.Console.Testing;
global using static Invex.Atom.Workflows.Tests.TestUtils.WorkflowTestUtils;
global using Target = Invex.Atom.Build.Definition.Target;
