global using DecSm.Atom.Args;
global using DecSm.Atom.Artifacts;
global using DecSm.Atom.Build;
global using DecSm.Atom.Build.BuildOptions;
global using DecSm.Atom.Build.Definition;
global using DecSm.Atom.Module.GithubWorkflows.Extensions;
global using DecSm.Atom.Module.GithubWorkflows.Helpers;
global using DecSm.Atom.Module.GithubWorkflows.Workflows.Dependabot.Model;
global using DecSm.Atom.Module.GithubWorkflows.Workflows.Github;
global using DecSm.Atom.Module.GithubWorkflows.Workflows.Github.Model;
global using DecSm.Atom.Params;
global using DecSm.Atom.Paths;
global using DecSm.Atom.TestUtils;
global using DecSm.Atom.Workflows.Definition;
global using DecSm.Atom.Workflows.Definition.Options;
global using DecSm.Atom.Workflows.Definition.Triggers;
global using DecSm.Atom.Workflows.Expressions;
global using DecSm.Atom.Workflows.Options;
global using DecSm.Atom.Workflows.Writer;
global using FakeItEasy;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using Shouldly;
global using Spectre.Console.Testing;
global using static DecSm.Atom.TestUtils.TestUtils;
global using Target = DecSm.Atom.Build.Definition.Target;
