global using System.Diagnostics;
global using System.Diagnostics.CodeAnalysis;
global using System.IO.Abstractions;
global using System.Linq.Expressions;
global using System.Reflection;
global using System.Runtime.CompilerServices;
global using System.Text;
global using System.Text.Json;
global using Invex.Atom.Build.Args;
global using Invex.Atom.Build.BuildInfo;
global using Invex.Atom.Build.Definition;
global using Invex.Atom.Build.Exceptions;
global using Invex.Atom.Build.FileSystem;
global using Invex.Atom.Build.Hosting;
global using Invex.Atom.Build.Logging;
global using Invex.Atom.Build.Model;
global using Invex.Atom.Build.Params;
global using Invex.Atom.Build.Reports;
global using Invex.Atom.Build.Secrets;
global using Invex.Atom.Build.Util;
global using Invex.Atom.Build.Util.Scope;
global using Invex.Atom.Build.Variables;
global using Invex.Atom.Build.Tests.BuildTests.Core;
global using Invex.Atom.TestUtils;
global using DiffEngine;
global using FakeItEasy;
global using JetBrains.Annotations;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using NUnit.Framework;
global using Shouldly;
global using Spectre.Console;
global using Spectre.Console.Testing;
global using static Invex.Atom.TestUtils.TestUtils;
global using IHelpService = Invex.Atom.Build.Help.IHelpService;
global using Target = Invex.Atom.Build.Definition.Target;
