namespace DecSm.Atom.Module.Dotnet.Model;

/// <summary>
///     Represents the root element of a TRX (Test Results XML) file.
/// </summary>
/// <remarks>
///     This model is used for deserializing TRX files generated by `dotnet test`
///     to extract test results and summary information.
/// </remarks>
[PublicAPI]
[XmlRoot(ElementName = "TestRun", Namespace = "http://microsoft.com/schemas/VisualStudio/TeamTest/2010")]
[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)]
public sealed record TestRun
{
    /// <summary>
    ///     Gets the unique identifier for the test run.
    /// </summary>
    [XmlAttribute(AttributeName = "id")]
    public string Id { get; init; } = string.Empty;

    /// <summary>
    ///     Gets the name of the test run.
    /// </summary>
    [XmlAttribute(AttributeName = "name")]
    public string Name { get; init; } = string.Empty;

    /// <summary>
    ///     Gets the user who initiated the test run.
    /// </summary>
    [XmlAttribute(AttributeName = "runUser")]
    public string RunUser { get; init; } = string.Empty;

    /// <summary>
    ///     Gets the time-related information for the test run.
    /// </summary>
    [XmlElement(ElementName = "Times")]
    public Times Times { get; init; } = new();

    /// <summary>
    ///     Gets the settings used for the test run.
    /// </summary>
    [XmlElement(ElementName = "TestSettings")]
    public TestSettings TestSettings { get; init; } = new();

    /// <summary>
    ///     Gets a list of individual unit test results.
    /// </summary>
    [XmlArray(ElementName = "Results")]
    [XmlArrayItem(ElementName = "UnitTestResult")]
    public List<UnitTestResult> Results { get; init; } = [];

    /// <summary>
    ///     Gets a list of unit test definitions.
    /// </summary>
    [XmlArray(ElementName = "TestDefinitions")]
    [XmlArrayItem(ElementName = "UnitTest")]
    public List<UnitTest> TestDefinitions { get; init; } = [];

    /// <summary>
    ///     Gets a list of test entries.
    /// </summary>
    [XmlArray(ElementName = "TestEntries")]
    [XmlArrayItem(ElementName = "TestEntry")]
    public List<TestEntry> TestEntries { get; init; } = [];

    /// <summary>
    ///     Gets a list of test lists.
    /// </summary>
    [XmlArray(ElementName = "TestLists")]
    [XmlArrayItem(ElementName = "TestList")]
    public List<TestList> TestLists { get; init; } = [];

    /// <summary>
    ///     Gets the summary of the test run results.
    /// </summary>
    [XmlElement(ElementName = "ResultSummary")]
    public ResultSummary ResultSummary { get; init; } = new();
}

/// <summary>
///     Represents time-related attributes of a test run.
/// </summary>
[PublicAPI]
[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)]
public sealed record Times
{
    /// <summary>
    ///     Gets the creation timestamp of the test run.
    /// </summary>
    [XmlAttribute(AttributeName = "creation")]
    public DateTime Creation { get; init; }

    /// <summary>
    ///     Gets the queuing timestamp of the test run.
    /// </summary>
    [XmlAttribute(AttributeName = "queuing")]
    public DateTime Queuing { get; init; }

    /// <summary>
    ///     Gets the start timestamp of the test run.
    /// </summary>
    [XmlAttribute(AttributeName = "start")]
    public DateTime Start { get; init; }

    /// <summary>
    ///     Gets the finish timestamp of the test run.
    /// </summary>
    [XmlAttribute(AttributeName = "finish")]
    public DateTime Finish { get; init; }
}

/// <summary>
///     Represents the test settings used for a test run.
/// </summary>
[PublicAPI]
[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)]
public sealed record TestSettings
{
    /// <summary>
    ///     Gets the name of the test settings.
    /// </summary>
    [XmlAttribute(AttributeName = "name")]
    public string Name { get; init; } = string.Empty;

    /// <summary>
    ///     Gets the unique identifier for the test settings.
    /// </summary>
    [XmlAttribute(AttributeName = "id")]
    public string Id { get; init; } = string.Empty;

    /// <summary>
    ///     Gets the deployment information for the test run.
    /// </summary>
    [XmlElement(ElementName = "Deployment")]
    public Deployment Deployment { get; init; } = new();
}

/// <summary>
///     Represents deployment-related information for a test run.
/// </summary>
[PublicAPI]
[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)]
public sealed record Deployment
{
    /// <summary>
    ///     Gets the root directory for deployment.
    /// </summary>
    [XmlAttribute(AttributeName = "runDeploymentRoot")]
    public string RunDeploymentRoot { get; init; } = string.Empty;
}

/// <summary>
///     Represents the result of a single unit test.
/// </summary>
[PublicAPI]
[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)]
public sealed record UnitTestResult
{
    /// <summary>
    ///     Gets the execution ID of the unit test.
    /// </summary>
    [XmlAttribute(AttributeName = "executionId")]
    public string ExecutionId { get; init; } = string.Empty;

    /// <summary>
    ///     Gets the ID of the test definition.
    /// </summary>
    [XmlAttribute(AttributeName = "testId")]
    public string TestId { get; init; } = string.Empty;

    /// <summary>
    ///     Gets the name of the test.
    /// </summary>
    [XmlAttribute(AttributeName = "testName")]
    public string TestName { get; init; } = string.Empty;

    /// <summary>
    ///     Gets the name of the computer where the test was run.
    /// </summary>
    [XmlAttribute(AttributeName = "computerName")]
    public string ComputerName { get; init; } = string.Empty;

    /// <summary>
    ///     Gets the duration of the test execution.
    /// </summary>
    [XmlAttribute(AttributeName = "duration")]
    public string Duration { get; init; } = string.Empty;

    /// <summary>
    ///     Gets the start time of the test execution.
    /// </summary>
    [XmlAttribute(AttributeName = "startTime")]
    public DateTime StartTime { get; init; }

    /// <summary>
    ///     Gets the end time of the test execution.
    /// </summary>
    [XmlAttribute(AttributeName = "endTime")]
    public DateTime EndTime { get; init; }

    /// <summary>
    ///     Gets the type of the test.
    /// </summary>
    [XmlAttribute(AttributeName = "testType")]
    public string TestType { get; init; } = string.Empty;

    /// <summary>
    ///     Gets the outcome of the test (e.g., "Passed", "Failed", "NotExecuted").
    /// </summary>
    [XmlAttribute(AttributeName = "outcome")]
    public string Outcome { get; init; } = string.Empty;

    /// <summary>
    ///     Gets the ID of the test list to which this test belongs.
    /// </summary>
    [XmlAttribute(AttributeName = "testListId")]
    public string TestListId { get; init; } = string.Empty;

    /// <summary>
    ///     Gets the relative directory for the test results.
    /// </summary>
    [XmlAttribute(AttributeName = "relativeResultsDirectory")]
    public string RelativeResultsDirectory { get; init; } = string.Empty;

    /// <summary>
    ///     Gets the output generated by the test.
    /// </summary>
    [XmlElement(ElementName = "Output")]
    public ResultOutput Output { get; init; } = new();
}

/// <summary>
///     Represents the output section of a test result.
/// </summary>
[PublicAPI]
[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)]
public sealed record ResultOutput
{
    /// <summary>
    ///     Gets error information if the test failed.
    /// </summary>
    [XmlElement(ElementName = "ErrorInfo")]
    public ErrorInfo ErrorInfo { get; init; } = new();
}

/// <summary>
///     Represents error information for a failed test.
/// </summary>
[PublicAPI]
[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)]
public sealed record ErrorInfo
{
    /// <summary>
    ///     Gets the error message.
    /// </summary>
    [XmlElement(ElementName = "Message")]
    public string Message { get; init; } = string.Empty;

    /// <summary>
    ///     Gets the stack trace of the error.
    /// </summary>
    [XmlElement(ElementName = "StackTrace")]
    public string StackTrace { get; init; } = string.Empty;

    /// <summary>
    ///     Gets the standard output captured during the error.
    /// </summary>
    [XmlElement(ElementName = "StdOut")]
    public string StdOut { get; init; } = string.Empty;

    /// <summary>
    ///     Gets the standard error captured during the error.
    /// </summary>
    [XmlElement(ElementName = "StdErr")]
    public string StdErr { get; init; } = string.Empty;
}

/// <summary>
///     Represents the definition of a unit test.
/// </summary>
[PublicAPI]
[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)]
public sealed record UnitTest
{
    /// <summary>
    ///     Gets the name of the unit test.
    /// </summary>
    [XmlAttribute(AttributeName = "name")]
    public string Name { get; init; } = string.Empty;

    /// <summary>
    ///     Gets the storage location of the test assembly.
    /// </summary>
    [XmlAttribute(AttributeName = "storage")]
    public string Storage { get; init; } = string.Empty;

    /// <summary>
    ///     Gets the unique identifier for the unit test definition.
    /// </summary>
    [XmlAttribute(AttributeName = "id")]
    public string Id { get; init; } = string.Empty;

    /// <summary>
    ///     Gets the execution details for the unit test.
    /// </summary>
    [XmlElement(ElementName = "Execution")]
    public Execution Execution { get; init; } = new();

    /// <summary>
    ///     Gets the method information for the unit test.
    /// </summary>
    [XmlElement(ElementName = "TestMethod")]
    public TestMethod TestMethod { get; init; } = new();
}

/// <summary>
///     Represents execution-related details of a unit test.
/// </summary>
[PublicAPI]
[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)]
public sealed record Execution
{
    /// <summary>
    ///     Gets the unique identifier for the test execution.
    /// </summary>
    [XmlAttribute(AttributeName = "id")]
    public string Id { get; init; } = string.Empty;
}

/// <summary>
///     Represents the method information of a unit test.
/// </summary>
[PublicAPI]
[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)]
public sealed record TestMethod
{
    /// <summary>
    ///     Gets the code base of the test assembly.
    /// </summary>
    [XmlAttribute(AttributeName = "codeBase")]
    public string CodeBase { get; init; } = string.Empty;

    /// <summary>
    ///     Gets the type name of the test adapter.
    /// </summary>
    [XmlAttribute(AttributeName = "adapterTypeName")]
    public string AdapterTypeName { get; init; } = string.Empty;

    /// <summary>
    ///     Gets the fully qualified class name of the test method.
    /// </summary>
    [XmlAttribute(AttributeName = "className")]
    public string ClassName { get; init; } = string.Empty;

    /// <summary>
    ///     Gets the name of the test method.
    /// </summary>
    [XmlAttribute(AttributeName = "name")]
    public string Name { get; init; } = string.Empty;
}

/// <summary>
///     Represents an entry in a test list, linking a test definition to an execution.
/// </summary>
[PublicAPI]
[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)]
public sealed record TestEntry
{
    /// <summary>
    ///     Gets the ID of the test definition.
    /// </summary>
    [XmlAttribute(AttributeName = "testId")]
    public string TestId { get; init; } = string.Empty;

    /// <summary>
    ///     Gets the execution ID associated with this test entry.
    /// </summary>
    [XmlAttribute(AttributeName = "executionId")]
    public string ExecutionId { get; init; } = string.Empty;

    /// <summary>
    ///     Gets the ID of the test list to which this entry belongs.
    /// </summary>
    [XmlAttribute(AttributeName = "testListId")]
    public string TestListId { get; init; } = string.Empty;
}

/// <summary>
///     Represents a test list.
/// </summary>
[PublicAPI]
[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)]
public sealed record TestList
{
    /// <summary>
    ///     Gets the name of the test list.
    /// </summary>
    [XmlAttribute(AttributeName = "name")]
    public string Name { get; init; } = string.Empty;

    /// <summary>
    ///     Gets the unique identifier for the test list.
    /// </summary>
    [XmlAttribute(AttributeName = "id")]
    public string Id { get; init; } = string.Empty;
}

/// <summary>
///     Represents the summary of test results for a test run.
/// </summary>
[PublicAPI]
[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)]
public sealed record ResultSummary
{
    /// <summary>
    ///     Gets the overall outcome of the test run (e.g., "Completed", "Failed").
    /// </summary>
    [XmlAttribute(AttributeName = "outcome")]
    public string Outcome { get; init; } = string.Empty;

    /// <summary>
    ///     Gets the counters for various test outcomes.
    /// </summary>
    [XmlElement(ElementName = "Counters")]
    public Counters Counters { get; init; } = new();

    /// <summary>
    ///     Gets the output associated with the result summary.
    /// </summary>
    [XmlElement(ElementName = "Output")]
    public Output Output { get; init; } = new();

    /// <summary>
    ///     Gets a list of collector data entries.
    /// </summary>
    [XmlArray(ElementName = "CollectorDataEntries")]
    [XmlArrayItem(ElementName = "Collector")]
    public List<Collector> CollectorDataEntries { get; init; } = [];
}

/// <summary>
///     Represents counters for different test outcomes in a test run.
/// </summary>
[PublicAPI]
[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)]
public sealed record Counters
{
    /// <summary>
    ///     Gets the total number of tests.
    /// </summary>
    [XmlAttribute(AttributeName = "total")]
    public int Total { get; init; }

    /// <summary>
    ///     Gets the number of executed tests.
    /// </summary>
    [XmlAttribute(AttributeName = "executed")]
    public int Executed { get; init; }

    /// <summary>
    ///     Gets the number of passed tests.
    /// </summary>
    [XmlAttribute(AttributeName = "passed")]
    public int Passed { get; init; }

    /// <summary>
    ///     Gets the number of failed tests.
    /// </summary>
    [XmlAttribute(AttributeName = "failed")]
    public int Failed { get; init; }

    /// <summary>
    ///     Gets the number of tests that resulted in an error.
    /// </summary>
    [XmlAttribute(AttributeName = "error")]
    public int Error { get; init; }

    /// <summary>
    ///     Gets the number of tests that timed out.
    /// </summary>
    [XmlAttribute(AttributeName = "timeout")]
    public int Timeout { get; init; }

    /// <summary>
    ///     Gets the number of aborted tests.
    /// </summary>
    [XmlAttribute(AttributeName = "aborted")]
    public int Aborted { get; init; }

    /// <summary>
    ///     Gets the number of inconclusive tests.
    /// </summary>
    [XmlAttribute(AttributeName = "inconclusive")]
    public int Inconclusive { get; init; }

    /// <summary>
    ///     Gets the number of tests that passed but whose run was aborted.
    /// </summary>
    [XmlAttribute(AttributeName = "passedButRunAborted")]
    public int PassedButRunAborted { get; init; }

    /// <summary>
    ///     Gets the number of tests that are not runnable.
    /// </summary>
    [XmlAttribute(AttributeName = "notRunnable")]
    public int NotRunnable { get; init; }

    /// <summary>
    ///     Gets the number of tests that were not executed.
    /// </summary>
    [XmlAttribute(AttributeName = "notExecuted")]
    public int NotExecuted { get; init; }

    /// <summary>
    ///     Gets the number of tests that were disconnected.
    /// </summary>
    [XmlAttribute(AttributeName = "disconnected")]
    public int Disconnected { get; init; }

    /// <summary>
    ///     Gets the number of tests that resulted in a warning.
    /// </summary>
    [XmlAttribute(AttributeName = "warning")]
    public int Warning { get; init; }

    /// <summary>
    ///     Gets the number of completed tests.
    /// </summary>
    [XmlAttribute(AttributeName = "completed")]
    public int Completed { get; init; }

    /// <summary>
    ///     Gets the number of tests currently in progress.
    /// </summary>
    [XmlAttribute(AttributeName = "inProgress")]
    public int InProgress { get; init; }

    /// <summary>
    ///     Gets the number of pending tests.
    /// </summary>
    [XmlAttribute(AttributeName = "pending")]
    public int Pending { get; init; }
}

/// <summary>
///     Represents the output section of a test result summary.
/// </summary>
[PublicAPI]
[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)]
public sealed record Output
{
    /// <summary>
    ///     Gets the standard output captured during the test run.
    /// </summary>
    [XmlElement(ElementName = "StdOut")]
    public string StdOut { get; init; } = string.Empty;
}

/// <summary>
///     Represents data collected by a test data collector.
/// </summary>
[PublicAPI]
[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)]
public sealed record Collector
{
    /// <summary>
    ///     Gets the name of the agent that collected the data.
    /// </summary>
    [XmlAttribute(AttributeName = "agentName")]
    public string AgentName { get; init; } = string.Empty;

    /// <summary>
    ///     Gets the URI of the data collector.
    /// </summary>
    [XmlAttribute(AttributeName = "uri")]
    public string Uri { get; init; } = string.Empty;

    /// <summary>
    ///     Gets the display name of the data collector.
    /// </summary>
    [XmlAttribute(AttributeName = "collectorDisplayName")]
    public string CollectorDisplayName { get; init; } = string.Empty;

    /// <summary>
    ///     Gets a list of URI attachments associated with the collector data.
    /// </summary>
    [XmlArray(ElementName = "UriAttachments")]
    [XmlArrayItem(ElementName = "UriAttachment")]
    public List<UriAttachment> UriAttachments { get; init; } = [];
}

/// <summary>
///     Represents a URI attachment within collector data.
/// </summary>
[PublicAPI]
[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)]
public sealed record UriAttachment
{
    /// <summary>
    ///     Gets the attachment details.
    /// </summary>
    [XmlElement(ElementName = "A")]
    public A A { get; init; } = new();
}

/// <summary>
///     Represents an attachment with a hyperlink reference.
/// </summary>
[PublicAPI]
[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)]
public sealed record A
{
    /// <summary>
    ///     Gets the hyperlink reference.
    /// </summary>
    [XmlAttribute(AttributeName = "href")]
    public string Href { get; init; } = string.Empty;
}
