global using Invex.Atom.Build;
global using Invex.Atom.Build.Args;
global using Invex.Atom.Build.Artifacts;
global using Invex.Atom.Build.BuildOptions;
global using Invex.Atom.Build.Definition;
global using Invex.Atom.Build.Hosting;
global using Invex.Atom.Build.Params;
global using Invex.Atom.Module.GithubWorkflows.Extensions;
global using Invex.Atom.Module.GithubWorkflows.Helpers;
global using Invex.Atom.Module.GithubWorkflows.Options;
global using Invex.Atom.TestUtils;
global using Invex.Atom.Workflows;
global using Invex.Atom.Workflows.Definition;
global using Invex.Atom.Workflows.Definition.Triggers;
global using Invex.Atom.Workflows.Options;
global using Invex.StructuredText.GithubActions.DependabotConfigModel.Model;
global using Invex.StructuredText.GithubActions.GithubActionModel;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Shouldly;
global using Spectre.Console.Testing;
global using static Invex.Atom.TestUtils.TestUtils;
global using Target = Invex.Atom.Build.Definition.Target;
