global using System.Reflection;
global using DecSm.Atom.Build.Args;
global using DecSm.Atom.Build.BuildOptions;
global using DecSm.Atom.Build.Definition;
global using DecSm.Atom.Build.Hosting;
global using DecSm.Atom.Build.Model;
global using DecSm.Atom.Build.Params;
global using DecSm.Atom.TestUtils;
global using DecSm.Atom.Workflows;
global using DecSm.Atom.Workflows.Definition;
global using DecSm.Atom.Workflows.Definition.Triggers;
global using DecSm.Atom.Workflows.Model;
global using DecSm.Atom.Workflows.Options;
global using DecSm.Atom.Workflows.Options.Injections;
global using DecSm.Atom.Workflows.TestUtils;
global using DecSm.Atom.Workflows.Writer;
global using DecSm.StructuredText.Expressions;
global using FakeItEasy;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using NUnit.Framework;
global using Shouldly;
global using Spectre.Console.Testing;
global using static DecSm.Atom.TestUtils.TestUtils;
global using Target = DecSm.Atom.Build.Definition.Target;
