global using System.IO.Abstractions.TestingHelpers;
global using DecSm.Atom.Build.Args;
global using DecSm.Atom.Build.BuildOptions;
global using DecSm.Atom.Build.Definition;
global using DecSm.Atom.Build.Exceptions;
global using DecSm.Atom.Build.Params;
global using DecSm.Atom.TestUtils;
global using DecSm.Atom.Workflows.Definition;
global using DecSm.Atom.Workflows.Definition.Triggers;
global using DecSm.Atom.Workflows.Model;
global using DecSm.Atom.Workflows.Tests.Builds;
global using DecSm.Atom.Workflows.Tests.TestUtils;
global using DecSm.Atom.Workflows.Writer;
global using JetBrains.Annotations;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using NUnit.Framework;
global using Shouldly;
global using Spectre.Console.Testing;
global using static DecSm.Atom.Workflows.Tests.TestUtils.WorkflowTestUtils;
global using Target = DecSm.Atom.Build.Definition.Target;
