// ReSharper disable ForeachCanBeConvertedToQueryUsingAnotherGetEnumerator - Perf
// ReSharper disable ForeachCanBePartlyConvertedToQueryUsingAnotherGetEnumerator - Perf

namespace DecSm.Atom.SourceGenerators;

[Generator]
public sealed class BuildDefinitionSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classSymbols = context
            .SyntaxProvider
            .ForAttributeWithMetadataName(BuildDefinitionAttribute,
                static (node, _) => node is ClassDeclarationSyntax,
                static (context, _) => (INamedTypeSymbol)context.TargetSymbol)
            .WithTrackingName(nameof(GenerateInterfaceMembersSourceGenerator));

        context.RegisterSourceOutput(classSymbols.Select(static (symbol, ct) => GeneratePartial(symbol, ct)),
            static (context, data) =>
            {
                if (data.SourceCode is not null)
                    context.AddSource($"{data.ClassName}.g.cs", SourceText.From(data.SourceCode, Encoding.UTF8));
            });
    }

    private static ClassNameWithSourceCode GeneratePartial(
        INamedTypeSymbol classSymbol,
        CancellationToken cancellationToken)
    {
        var namespaceName = classSymbol.ContainingNamespace.ToDisplayString();
        var isGlobalNamespace = namespaceName is "<global namespace>";

        var allInterfaces = classSymbol.AllInterfaces;
        var (allTargets, allParams) = GetTargetsAndParams(classSymbol, allInterfaces);

        var configureHostMethod = GetConfigureHostMethod(allInterfaces);
        var configureHostBuilderMethod = GetConfigureBuilderMethod(allInterfaces);

        var inheritConfigureHostLine = configureHostMethod.Any || configureHostBuilderMethod.Any
            ? ", DecSm.Atom.Hosting.IConfigureHost"
            : string.Empty;

        var configureHostText = configureHostMethod.Any || configureHostBuilderMethod.Any
            ? configureHostMethod.Text
            : string.Empty;

        var configureHostBuilderText = configureHostMethod.Any || configureHostBuilderMethod.Any
            ? configureHostBuilderMethod.Text
            : string.Empty;

        cancellationToken.ThrowIfCancellationRequested();

        var sourceCode = BuildSourceCode(isGlobalNamespace
                ? string.Empty
                : $"global using static {classSymbol.ToDisplayString()};",
            isGlobalNamespace
                ? string.Empty
                : $"namespace {namespaceName};",
            classSymbol.Name,
            classSymbol.ToDisplayString(),
            inheritConfigureHostLine,
            [
                new("Targets",
                [
                    GetTargetDefinitionsField(allTargets),
                    GetTargetDefinitionsProperty(allTargets),
                    GetWorkflowTargetsClass(allTargets),
                    GetWorkflowTargetMethod(allTargets),
                ]),
                new("Params",
                [
                    GetParamDefinitionsField(allParams),
                    GetParamDefinitionsProperty(allParams),
                    GetParamsDataClass(allParams),
                    GetParamsField(),
                    GetWorkflowParamsProperty(allParams),
                    GetAccessParamMethod(allParams),
                ]),
                new("Host", [configureHostText, configureHostBuilderText]),
            ]);

        return new(classSymbol.Name, sourceCode);
    }

    private static string BuildSourceCode(
        string globalUsingStaticLine,
        string namespaceLine,
        string classNameSimple,
        string classNameFull,
        string configureHostInherit,
        CodeRegion[] codeRegions)
    {
        var sb = new StringBuilder();

        sb.AppendLine("""
                      // <auto-generated/>

                      #nullable enable

                      """);

        sb.AppendLineIfNotBlank(globalUsingStaticLine, null, string.Empty);

        sb.AppendLine("""
                      using System.Diagnostics.CodeAnalysis;
                      using System.Linq.Expressions;
                      using Microsoft.Extensions.DependencyInjection;
                      using Microsoft.Extensions.Logging;
                      using DecSm.Atom.Build.Definition;
                      using DecSm.Atom.Params;
                      using DecSm.Atom.Paths;
                      using DecSm.Atom.Process;

                      """);

        sb.AppendLineIfNotBlank(namespaceLine, null, string.Empty);

        sb.AppendLine($$"""
                        [JetBrains.Annotations.PublicAPI]
                        partial class {{classNameSimple}} : {{IBuildDefinition}}{{configureHostInherit}}
                        {
                        """);

        sb.AppendLine($$"""
                            public {{classNameSimple}}(System.IServiceProvider services) : base(services) { }

                            private ILogger Logger => Services.GetRequiredService<ILoggerFactory>().CreateLogger("{{classNameFull}}");

                            private IAtomFileSystem FileSystem => GetService<IAtomFileSystem>();

                            private IProcessRunner ProcessRunner => GetService<IProcessRunner>();

                            private T GetService<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.Interfaces)] T>()
                                where T : notnull =>
                                typeof(T).GetInterface(nameof(IBuildDefinition)) != null
                                    ? (T)(IBuildDefinition)this
                                    : Services.GetRequiredService<T>();

                            private IEnumerable<T> GetServices<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.Interfaces)] T>()
                                where T : notnull =>
                                typeof(T).GetInterface(nameof(IBuildDefinition)) != null
                                    ? [(T)(IBuildDefinition)this]
                                    : Services.GetServices<T>();

                            [return: NotNullIfNotNull(nameof(defaultValue))]
                            private T? GetParam<[DynamicallyAccessedMembers(DynamicallyAccessedMemberTypes.All)] T>(
                                Expression<Func<T?>> parameterExpression,
                                T? defaultValue = default,
                                Func<string?, T?>? converter = null) =>
                                    Services
                                        .GetRequiredService<IParamService>()
                                        .GetParam(parameterExpression, defaultValue, converter);
                        """);

        foreach (var codeRegion in codeRegions)
        {
            var appendRegion = false;

            foreach (var block in codeRegion.RegionBlocks)
                if (block.Length > 0)
                    appendRegion = true;

            if (!appendRegion)
                continue;

            sb.AppendLine();
            sb.AppendLine($"    #region {codeRegion.RegionName}");

            foreach (var fieldDeclaration in codeRegion.RegionBlocks)
                sb.AppendLineIfNotBlank(fieldDeclaration, string.Empty);

            sb.AppendLine();
            sb.AppendLine($"    #endregion {codeRegion.RegionName}");
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static TargetsAndParams GetTargetsAndParams(
        INamedTypeSymbol classSymbol,
        ImmutableArray<INamedTypeSymbol> allInterfaces)
    {
        var targetsBuilder = ImmutableArray.CreateBuilder<TargetData>(64);
        var paramsBuilder = ImmutableArray.CreateBuilder<ParamData>(64);
        HashSet<string> addedTargetNames = [];

        foreach (var memberSymbol in classSymbol.GetMembers())
            if (memberSymbol is IPropertySymbol propertySymbol)
            {
                if (propertySymbol.Type.ToDisplayString() is Target && addedTargetNames.Add(propertySymbol.Name))
                    targetsBuilder.Add(new(propertySymbol, classSymbol));

                foreach (var attributeData in propertySymbol.GetAttributes())
                {
                    if (attributeData.AttributeClass?.ToDisplayString() is not ParamDefinitionAttribute
                        and not SecretDefinitionAttribute)
                        continue;

                    paramsBuilder.Add(new(propertySymbol, attributeData, classSymbol));

                    break;
                }
            }

        foreach (var interfaceSymbol in allInterfaces)
        foreach (var memberSymbol in interfaceSymbol.GetMembers())
            if (memberSymbol is IPropertySymbol propertySymbol)
            {
                if (propertySymbol.Type.ToDisplayString() is Target && addedTargetNames.Add(propertySymbol.Name))
                    targetsBuilder.Add(new(propertySymbol, interfaceSymbol));

                foreach (var attributeData in propertySymbol.GetAttributes())
                {
                    if (attributeData.AttributeClass?.ToDisplayString() is not ParamDefinitionAttribute
                        and not SecretDefinitionAttribute)
                        continue;

                    paramsBuilder.Add(new(propertySymbol, attributeData, interfaceSymbol));

                    break;
                }
            }

        return new(targetsBuilder.ToImmutable(), paramsBuilder.ToImmutable());
    }

    private static string GetTargetDefinitionsField(ImmutableArray<TargetData> allTargets) =>
        allTargets.IsEmpty
            ? string.Empty
            : $"    private {IReadOnlyDictionary}<string, {Target}>? _targetDefinitions;";

    private static string GetParamDefinitionsField(ImmutableArray<ParamData> allParams)
    {
        if (allParams.IsEmpty)
            return string.Empty;

        var sb = new StringBuilder();

        sb.AppendLine(
            $"    private readonly {IReadOnlyDictionary}<string, {ParamDefinition}> _paramDefinitions = new {Dictionary}<string, {ParamDefinition}>()");

        sb.AppendLine("    {");

        foreach (var param in allParams)
        {
            var nameofExpression = $"nameof({param.Type.ToDisplayString()}.{param.Property.Name})";

            var argName = param
                .Attribute
                .ConstructorArguments[0]
                .Value
                ?.ToString();

            var description = param
                .Attribute
                .ConstructorArguments[1]
                .Value
                ?.ToString();

            var sources =
                $"({param.Attribute.ConstructorArguments[2].Type?.ToDisplayString()}){param.Attribute.ConstructorArguments[2].Value}";

            var isSecret = param.Attribute.AttributeClass?.ToDisplayString() is SecretDefinitionAttribute;

            var chainedParams = param.Attribute.ConstructorArguments.Length > 3
                ? param.Attribute.ConstructorArguments[3].Kind is TypedConstantKind.Array
                    ? param.Attribute.ConstructorArguments[3].Values
                    : []
                : [];

            sb.AppendLine("        {");
            sb.AppendLine($"            {nameofExpression}, new({nameofExpression})");
            sb.AppendLine("            {");
            sb.AppendLine($"""                ArgName = "{argName}",""");
            sb.AppendLine($"""                Description = "{description}",""");
            sb.AppendLine($"                Sources = {sources},");
            sb.AppendLine($"                IsSecret = {isSecret.ToString().ToLower()},");

            if (chainedParams.IsDefaultOrEmpty)
            {
                sb.AppendLine("                ChainedParams = [],");
            }
            else
            {
                sb.Append("                ChainedParams = [ ");

                foreach (var v in chainedParams)
                    sb.Append($"\"{v.Value?.ToString() ?? string.Empty}\", ");

                sb.AppendLine("],");
            }

            sb.AppendLine("            }");
            sb.AppendLine("        },");
        }

        sb.AppendLine("    };");

        return sb.ToString();
    }

    private static string GetParamsField() =>
        "    private ParamsData? _params;";

    private static string GetTargetDefinitionsProperty(ImmutableArray<TargetData> allTargets)
    {
        if (allTargets.IsEmpty)
            return
                $$"""    public override {{IReadOnlyDictionary}}<string, {{Target}}> TargetDefinitions { get; } = new {{Dictionary}}<string, {{Target}}>();""";

        var sb = new StringBuilder();

        sb.AppendLine(
            $"    public override {IReadOnlyDictionary}<string, Target> TargetDefinitions => _targetDefinitions ??= new {Dictionary}<string, Target>");

        sb.AppendLine("    {");

        foreach (var target in allTargets)
            sb.AppendLine(
                $$"""        { nameof({{target.Type.ToDisplayString()}}.{{target.Property.Name}}), (({{target.Type.ToDisplayString()}})this).{{target.Property.Name}} },""");

        sb.AppendLine("    };");

        return sb.ToString();
    }

    private static string GetParamDefinitionsProperty(ImmutableArray<ParamData> allParams) =>
        allParams.IsEmpty
            ? $$"""    public override {{IReadOnlyDictionary}}<string, {{ParamDefinition}}> ParamDefinitions { get; } = new {{Dictionary}}<string, {{ParamDefinition}}>();"""
            : $"    public override {IReadOnlyDictionary}<string, ParamDefinition> ParamDefinitions => _paramDefinitions;";

    private static string GetWorkflowTargetsClass(ImmutableArray<TargetData> allTargets)
    {
        if (allTargets.IsEmpty)
            return string.Empty;

        var sb = new StringBuilder();
        sb.AppendLine("    public static class WorkflowTargets");
        sb.AppendLine("    {");

        foreach (var target in allTargets)
            sb.AppendLine(
                $"        public static readonly {WorkflowTargetDefinition} {target.Property.Name} = new(nameof({target.Type.ToDisplayString()}.{target.Property.Name}));");

        sb.AppendLine("    }");

        return sb.ToString();
    }

    private static string GetWorkflowTargetMethod(ImmutableArray<TargetData> allTargets)
    {
        if (allTargets.IsEmpty)
            return
                $$"""private static {{WorkflowTargetDefinition}} Target(string name) => throw new System.ArgumentException($"Target with name '{name}' is not defined in the build definition.", nameof(name));""";

        var sb = new StringBuilder();

        sb.AppendLine($"    private static {WorkflowTargetDefinition} WorkflowTarget(string name) =>");
        sb.AppendLine("        name switch");
        sb.AppendLine("        {");

        foreach (var target in allTargets)
            sb.AppendLine(
                $"            nameof({target.Type.ToDisplayString()}.{target.Property.Name}) => WorkflowTargets.{target.Property.Name},");

        sb.AppendLine(
            """            _ => throw new System.ArgumentException($"Target with name '{name}' is not defined in the build definition.", nameof(name))""");

        sb.AppendLine("        };");

        return sb.ToString();
    }

    private static string GetParamsDataClass(ImmutableArray<ParamData> allParams)
    {
        if (allParams.IsEmpty)
            return "    public sealed class ParamsData() { }";

        var sb = new StringBuilder();
        sb.AppendLine($"    public sealed class ParamsData({IBuildDefinition} buildDefinition)");
        sb.AppendLine("    {");

        foreach (var param in allParams)
            sb.AppendLine(
                $"        public ParamDefinition {param.Property.Name} => buildDefinition.ParamDefinitions[nameof({param.Type.ToDisplayString()}.{param.Property.Name})];");

        sb.AppendLine("    }");

        return sb.ToString();
    }

    private static string GetWorkflowParamsProperty(ImmutableArray<ParamData> allParams) =>
        allParams.IsEmpty
            ? "    public ParamsData WorkflowParams => _params ??= new();"
            : "    public ParamsData WorkflowParams => _params ??= new(this);";

    private static string GetAccessParamMethod(ImmutableArray<ParamData> allParams)
    {
        if (allParams.IsEmpty)
            return
                """    public override object? AccessParam(string paramName) => throw new System.ArgumentException($"Param with name '{paramName}' is not defined in the build definition.", nameof(paramName));""";

        var sb = new StringBuilder();

        sb.AppendLine("    public override object? AccessParam(string paramName) =>");
        sb.AppendLine("        paramName switch");
        sb.AppendLine("        {");

        foreach (var param in allParams)
            sb.AppendLine(
                $"            nameof({param.Type.ToDisplayString()}.{param.Property.Name}) => (({param.Type.ToDisplayString()})this).{param.Property.Name},");

        sb.AppendLine(
            """            _ => throw new System.ArgumentException($"Param with name '{paramName}' is not defined in the build definition.", nameof(paramName))""");

        sb.AppendLine("        };");

        return sb.ToString();
    }

    private static TextResult GetConfigureHostMethod(ImmutableArray<INamedTypeSymbol> allInterfaces)
    {
        var configureHostInterfaces = new List<INamedTypeSymbol>(64);

        foreach (var interfaceSymbol in allInterfaces)
        foreach (var attributeData in interfaceSymbol.GetAttributes())
        {
            if (attributeData.AttributeClass?.ToDisplayString() is not ConfigureHostAttribute)
                continue;

            configureHostInterfaces.Add(interfaceSymbol);

            break;
        }

        if (configureHostInterfaces.Count is 0)
            return new("    public void ConfigureBuildHost(Microsoft.Extensions.Hosting.IHost builder) { }", false);

        var sb = new StringBuilder();

        sb.AppendLine("    public void ConfigureBuildHost(Microsoft.Extensions.Hosting.IHost builder)");
        sb.AppendLine("    {");

        foreach (var interfaceSymbol in configureHostInterfaces)
            sb.AppendLine($"        {interfaceSymbol.ToDisplayString()}.ConfigureHost(builder);");

        sb.AppendLine("    }");

        return new(sb.ToString(), true);
    }

    private static TextResult GetConfigureBuilderMethod(ImmutableArray<INamedTypeSymbol> allInterfaces)
    {
        var configureHostInterfaces = new List<INamedTypeSymbol>(64);
        var registerHostInterfaces = new List<INamedTypeSymbol>(64);

        foreach (var interfaceSymbol in allInterfaces)
        {
            foreach (var subInterfaceSymbol in interfaceSymbol.AllInterfaces)
            {
                if (subInterfaceSymbol.ToDisplayString() is not IBuildDefinition and not IBuildAccessor)
                    continue;

                registerHostInterfaces.Add(interfaceSymbol);

                break;
            }

            foreach (var attributeData in interfaceSymbol.GetAttributes())
            {
                if (attributeData.AttributeClass?.ToDisplayString() is not ConfigureHostBuilderAttribute)
                    continue;

                configureHostInterfaces.Add(interfaceSymbol);

                break;
            }
        }

        if (configureHostInterfaces.Count + registerHostInterfaces.Count is 0)
            return new(
                "    public void ConfigureBuildHostBuilder(Microsoft.Extensions.Hosting.IHostApplicationBuilder builder) { }",
                false);

        var sb = new StringBuilder();

        sb.AppendLine(
            "    public void ConfigureBuildHostBuilder(Microsoft.Extensions.Hosting.IHostApplicationBuilder builder)");

        sb.AppendLine("    {");

        foreach (var interfaceSymbol in registerHostInterfaces)
        {
            var interfaceFullName = interfaceSymbol.ToDisplayString();

            sb.AppendLine(
                $"        Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton<{interfaceFullName}>(builder.Services, static p => ({interfaceFullName})p.GetRequiredService<{IBuildDefinition}>());");
        }

        foreach (var interfaceSymbol in configureHostInterfaces)
            sb.AppendLine($"        {interfaceSymbol.ToDisplayString()}.ConfigureBuilder(builder);");

        sb.AppendLine("    }");

        return new(sb.ToString(), true);
    }
}

public static class StringBuilderExtensions
{
    public static void AppendLineIfNotBlank(
        this StringBuilder sb,
        string? value,
        string? conditionalPrefix = null,
        string? conditionalSuffix = null)
    {
        if (string.IsNullOrWhiteSpace(value))
            return;

        if (conditionalPrefix is not null)
            sb.AppendLine(conditionalPrefix);

        if (value?.EndsWith("\n") is true)
            sb.Append(value);
        else
            sb.AppendLine(value);

        if (conditionalSuffix is not null)
            sb.AppendLine(conditionalSuffix);
    }
}
