namespace DecSm.Atom.SourceGenerators;

[Generator]
public class GenerateEntryPointSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classSymbols = context
            .SyntaxProvider
            .ForAttributeWithMetadataName(GenerateEntryPointAttribute,
                static (node, _) => node is ClassDeclarationSyntax,
                static (attrContext, _) => (INamedTypeSymbol)attrContext.TargetSymbol)
            .WithTrackingName(nameof(GenerateEntryPointSourceGenerator));

        context.RegisterSourceOutput(classSymbols.Collect(), GenerateCode);
    }

    private static void GenerateCode(SourceProductionContext context, ImmutableArray<INamedTypeSymbol> classSymbols)
    {
        foreach (var classSymbol in classSymbols)
            GeneratePartial(context, classSymbol);
    }

    private static void GeneratePartial(SourceProductionContext context, INamedTypeSymbol classSymbol)
    {
        var code = $"""
                    // <auto-generated/>

                    DecSm.Atom.Hosting.AtomHost.Run<{classSymbol.ToDisplayString()}>(args);
                    """;

        context.AddSource($"{classSymbol.Name}.g.cs", SourceText.From(code, Encoding.UTF8));
    }
}
