namespace Invex.Atom.Build.SourceGenerators;

[Generator]
public class GenerateEntryPointSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classSymbols = context
            .SyntaxProvider
            .ForAttributeWithMetadataName(GenerateEntryPointAttribute,
                static (node, _) => node is ClassDeclarationSyntax or InterfaceDeclarationSyntax,
                static (attrContext, _) => (INamedTypeSymbol)attrContext.TargetSymbol)
            .WithTrackingName(nameof(GenerateEntryPointSourceGenerator));

        context.RegisterSourceOutput(classSymbols.Collect(), GenerateCode);
    }

    private static void GenerateCode(SourceProductionContext context, ImmutableArray<INamedTypeSymbol> classSymbols)
    {
        foreach (var classSymbol in classSymbols)
            GeneratePartial(context, classSymbol);
    }

    private static void GeneratePartial(SourceProductionContext context, INamedTypeSymbol classSymbol)
    {
        var typeName = classSymbol.ToDisplayString();

        // If it's an interface, we need to trim the "I" prefix from the last part
        var typeParts = typeName.Split('.');
        var lastPart = typeParts[typeParts.Length - 1];

        if (lastPart.StartsWith("I") && lastPart.Length > 1 && char.IsUpper(lastPart[1]))
            typeParts[typeParts.Length - 1] = lastPart.Substring(1);

        var trimmedTypeName = string.Join(".", typeParts);

        var code = $"""
                    // <auto-generated/>

                    Invex.Atom.Build.Hosting.AtomHost.Run<{trimmedTypeName}>(args);
                    """;

        context.AddSource($"{classSymbol.Name.TrimStart('I')}.g.cs", SourceText.From(code, Encoding.UTF8));
    }
}
